name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

        - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2' 

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$HOST $USERNAME" > ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          ssh -i ~/.ssh/id_rsa $USERNAME@$HOST << 'ENDSSH'
            cd program/fly-overhead
            git pull origin master
            cd client
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/npm install
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/npm run build
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/pm2 restart all
            cd ../server
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/npm install
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/pm2 restart all
          ENDSSH
